### ISSUE TITLE
Change the menu actions on the scripture card

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#43]
Right now menu actions on the scripture card are a bit confusing. We would like to have a quick way for people to add a note about someone from the main screen. However the existing menu action item (add note) only makes sense for a person card. How can we design a UX that makes sense in this area?

**Comment by calvinf** [comment]
I agree, with the current "pager" UI, it's confusing to have "Add note" menu action on the Scripture view's nav.  The menu action nav should be consistent within the same view and because of this I'd recommend removing the "Add note" menu option.

"Add note" is directly tied to a person and a person is contained within a card in the person view.  I'd remove the menu action from the nav and title bar and add it to the card instead.  For the scripture view, add a menu action that contains the "Share" action (rather than using the text currently displayed there) and any other actions relevant to the scripture.

**Comment by chrislim** [comment]
I think we resolved this for the release.
