### ISSUE TITLE
User cannot remove contacts from Ceaseless from "People" view

### ISSUE THREAD

**Issue by nylim11** [ceaseless-prayer/CeaselessAndroid#88]
User tried to remove contacts in Ceaseless via "People" view and was able to select contacts for removal, but there was no "REMOVE" text in the top right hand corner (instead, just a white bar across the top).

Typically expect a gray bar at the top with back arrow and "REMOVE" text in the top right hand corner.

User was able to remove individual contacts by tapping on the contact's image, but not the way outlined above.

Attached screenshot for reference:
![screenshot_2016-08-22-17-17-04](https://cloud.githubusercontent.com/assets/15037189/17873222/0d7b79f2-6879-11e6-810e-07890cc6044d.png)

**Comment by nylim11** [comment]
Update: the user was able to tap on the top right hand corner and it was able to remove contacts. Given this, it may be more of a formatting issue - the white background color that appears in this case is causing the problem.

**Comment by chrislim** [comment]
@evandyang here is a second issue you can look into.
Basically: tapping and holding on a contact or on a note in order to delete it highlights the line with all white, which washes out the text so it isn't readable. One fix would be to make the highlighted text dark so that the user can still see what they have selected.

**Comment by chrislim** [comment]
Resolved in latest release.
